name: CI

on:
  pull_request:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup

      - name: Lint
        run: make lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup

      - name: Type check
        run: make types

  test-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup

      - name: Unit tests
        run: make test-back

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            coverage.xml
            report.xml

  test-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup

      - name: Install Playwright Chromium
        run: make playwright-install

      - name: E2E tests
        run: make test-front

  check:
    runs-on: ubuntu-latest
    needs: [lint, type-check, test-back, test-front]
    if: always()
    steps:
      - name: Check all jobs result
        run: |
          test "${{ needs.lint.result }}" = "success"
          test "${{ needs.type-check.result }}" = "success"
          test "${{ needs.test-back.result }}" = "success"
          test "${{ needs.test-front.result }}" = "success"